<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>preview</LangVersion>
    <RootNamespace>LootingBots</RootNamespace>
    <AssemblyName>skwizzy.LootingBots</AssemblyName>
    <Version>1.7.0</Version>
    <ReleaseOutputDir>..\Build\BepInEx\plugins\</ReleaseOutputDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.43" IncludeAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.25.*-*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.*-*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.*-*" PrivateAssets="all" />
    <PackageReference Include="RoR2.BepInEx.Analyzers" Version="1.0.*-*" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="DrakiaXYZ-BigBrain">
      <HintPath>..\References\DrakiaXYZ-BigBrain.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\References\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>..\References\spt-common.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\References\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\References\hollowed.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\References\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="ItemComponent.Types" HintPath="..\References\ItemComponent.Types.dll" Private="False" />
    <Reference Include="Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\References\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="DissonanceVoip" HintPath="..\References\DissonanceVoip.dll" Private="False" />
    <Reference Include="UniTask">
      <HintPath>..\References\UnityToolkit\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="UniTask.Addressables">
      <HintPath>..\References\UnityToolkit\UniTask.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="UniTask.DOTween">
      <HintPath>..\References\UnityToolkit\UniTask.DOTween.dll</HintPath>
    </Reference>
    <Reference Include="UniTask.Linq">
      <HintPath>..\References\UnityToolkit\UniTask.Linq.dll</HintPath>
    </Reference>
    <Reference Include="UniTask.TextMeshPro">
      <HintPath>..\References\UnityToolkit\UniTask.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\References\UnityToolkit\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="UnityToolkit">
      <HintPath>..\References\UnityToolkit\UnityToolkit.dll</HintPath>
    </Reference>
    <Reference Include="VContainer">
      <HintPath>..\References\UnityToolkit\VContainer.dll</HintPath>
    </Reference>
    <Reference Include="ZLinq">
      <HintPath>..\References\UnityToolkit\ZLinq.dll</HintPath>
    </Reference>
    <Reference Include="ZLinq.Unity">
      <HintPath>..\References\UnityToolkit\ZLinq.Unity.dll</HintPath>
    </Reference>
    <Reference Include="ZLinq.Unity.UnityCollectoins">
      <HintPath>..\References\UnityToolkit\ZLinq.Unity.UnityCollectoins.dll</HintPath>
    </Reference>
    <Reference Include="ZString">
      <HintPath>..\References\UnityToolkit\ZString.dll</HintPath>
    </Reference>
  </ItemGroup>
  <!-- Build script for release build-->
  <Target Name="CleanUnwantedFiles" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <AllFiles Include="$(OutputPath)**\*" />
      <FilesToKeep Include="$(OutputPath)$(TargetFileName)" />
      <FilesToKeep Include="$(OutputPath)$(TargetName).pdb" />
    </ItemGroup>
    <ItemGroup>
      <FilesToDelete Include="@(AllFiles)" Exclude="@(FilesToKeep)" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" />
  </Target>
  <Target Name="CopyBuildOutput" AfterTargets="CleanUnwantedFiles" Condition="'$(Configuration)' == 'Release'">
    <MakeDir Directories="$(ReleaseOutputDir)" />
    <ItemGroup>
      <RemainingFiles Include="$(OutputPath)**\*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(RemainingFiles)"
      DestinationFiles="@(RemainingFiles-&gt;'$(ReleaseOutputDir)%(RecursiveDir)%(Filename)%(Extension)')"
    />
  </Target>
</Project>
